# Generated by Django 5.2.6 on 2026-03-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='repeat',
            field=models.CharField(choices=[('none', 'Does not repeat'), ('daily', 'Daily'), ('weekly', 'Weekly on Friday'), ('monthly', 'Monthly on day 13'), ('annually', 'Annually on March 13'), ('custom', 'Custom')], default='none', max_length=20),
        ),
    ]
