# Generated by Django 5.2.6 on 2026-03-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_all_day_task_repeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
